server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    whitelabel:
      enabled: false

spring:
  #Mariadb
  # yml파이
  profiles:
    active: local

  datasource:
    url: jdbc:mariadb://localhost:3306/mysql_local?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&socketTimeout=10000&connectTimeout=10000
    username: root
    password: P@ssw0rd
  #    hikari:
  #      connection-timeout: 250
  #      max-lifetime: 500
  mvc:
    view:
      suffix: .html

#Devtool
devtools:
  livereload:
    enabled: true

#Logging
logging.level:
  root: info
  org.springframework:
    web: info
    security: info
    boot: info
  org.hibernate:
    SQL: debug
  org.swmaestro.demo: debug
